### ISSUE TITLE
unable to install jupyter_iframe for jupyterLab 1.2.X

### ISSUE THREAD

**Issue by sag31Bamane** [timkpaine/jupyterlab_iframe#119]
**Describe the bug**
I am trying to install jupyetr_iframe by following instruction here : https://pypi.org/project/jupyterlab-iframe/

pip install jupyterlab_iframe
jupyter labextension install jupyterlab_iframe
jupyter serverextension enable --py jupyterlab_iframe

**To Reproduce**
1. We need jupyterLab version 1.2.X
2. pip install jupyter_iframe should work 
3. try running "jupyter labextension install jupyterlab_iframe".
4. you should get Error Message ""jupyterlab_iframe" is not a valid npm package" 

**Expected behavior**
installation should succeed and able to load iframe in seperate browser tab.

**Comment by timkpaine** [comment]
You'll need to install an older version if you want it to work with jupyterlab 1.2, and you'll need to specify that older version in your pip and lab extension install commands

**Comment by sag31Bamane** [comment]
any input around which older  version works well with jupyterLab 1.2.x?

**Comment by timkpaine** [comment]
Not really, my only suggestion is upgrade jupyterlab, the older you let it get the more troubles you'll have.
