### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by jhgoebbert** [timkpaine/jupyterlab_iframe#12]
Hi timkpaine,

thanks for the very useful extension.
I use it as part of the Jupyter/JupyterHub installation on our HPC clusters.

Is it possible to allow a default page to open in a tab on startup of jupyter using jupyterlab_iframe?
I would like to use this for a welcome page to introduce new users to the possibilities of JupyterLab.

Best,
Jens Henrik

**Comment by timkpaine** [comment]
That's probably possible. Let me work out a good implementation

**Comment by jhgoebbert** [comment]
Thanks a lot ... let me know, if I can help.

**Comment by timkpaine** [comment]
https://www.npmjs.com/package/jupyterlab_iframe
