### ISSUE TITLE
Failed to load webpade

### ISSUE THREAD

**Issue by LeviZell** [timkpaine/jupyterlab_iframe#24]
When I enter a url the windows opens but it is blank. 

Looking at the JS console in chrome I see: 

Refused to display 'https://www.google.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

and trying another site I get:

Refused to display 'https://trello.com/' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by timkpaine** [comment]
those websites won't let you embed them in other websites.
