### ISSUE TITLE
jupyterlab_iframe quirks with JupyterLab 0.35.2

### ISSUE THREAD

**Issue by vishnu2kmohan** [timkpaine/jupyterlab_iframe#26]
Hi Tim,

I've incorporated your exceedingly useful extension into a [Docker](https://github.com/dcos-labs/dcos-jupyterlab-service/blob/DCOS-40453/Dockerfile#L272-L283) [Image](https://github.com/dcos-labs/dcos-jupyterlab-service/blob/DCOS-40453/jupyter-root-conda-base-env.yml#L135) but have been running into issues while trying to dock/layout iFrame tabs and it appears to be stealing/hogging focus away from other phosphor widgets while it's running.

e.g., I can't reliably re-arrange/tile the workspace and layout tabs if the extension is actively in use and displaying iFrames.

To reproduce:
```
docker run --rm -it -e ENABLE_SPARK_MONITOR=True -e START_SPARK_HISTORY=True -e START_TENSORBOARD=True
-e START_DASK_DISTRIBUTED=True -e START_RAY_HEAD_NODE=True -p 8080:8080 dcoslabs/dcos-jupyterlab:latest start.sh jupyter lab --NotebookApp.token=
'' --NotebookApp.password=''
```

Point your browser to `http://<hostname>:8080`
Now open up iFrames for `http://<hostname>:8080/tensorboard` and `http://<hostname>:8080/sparkhistory/` (trailing slash is required) and try to tile/arrange the iFrame tabs to have them laid out any which way you like and notice it's very hard to get it to go and stay just where you want them.

In addition, it sometimes becomes hard to re-launch notebooks that are running in the background but not actively being displayed if the extension is in use.

This is a very valuable extension that should ideally become a core part of JupyterLab, thank you very much for putting it together.

**Comment by timkpaine** [comment]
This is a known issue, its annoying to make iframes play nicely with phosphor. For tensor board, I recommend looking into the dedicated jupyterlab extension. Alternatively, if you know of a good way of making this work (maybe @sccolbert knows more) I'm more than happy to fix it.

**Comment by timkpaine** [comment]
@vishnu2kmohan this should be fixed
