### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by dhirschfeld** [timkpaine/jupyterlab_iframe#32]
Looks like @ian-r-rose is implementing this upstream:
https://github.com/jupyterlab/jupyterlab/pull/5855

**Comment by ian-r-rose** [comment]
Don't mean to step on your toes @timkpaine, and what I have done is definitely less featureful than your extension here. My primary goal is to get a reasonable live-editing of local HTML documents. I'd love to hear your thoughts on the PR against core JupyterLab.

**Comment by timkpaine** [comment]
I'm working on proxying #31 

I don't have any interest in a html viewer, only the ability to view other sites. Ideally this will allow http over https and vice versa. So i think for now this is more of a replacement for jupyterlab_html not this package.

**Comment by dhirschfeld** [comment]
I just opened this issue as a user of Tim's extension. Thanks for chiming in - it helps me know whether or not I still need to install this extension as well as the upstream version...

**Comment by ian-r-rose** [comment]
My PR has some overlap with this extension, but I've been waffling about whether to keep it there. The iframe-ing will certainly work better with a proxy like the one here.
