### ISSUE TITLE
tornado>=6

### ISSUE THREAD

**Issue by jhgoebbert** [timkpaine/jupyterlab_iframe#38]
With the requirement of tornado 6.x the version 0.0.12 is limited to jupyter installations which can handle tornado 6.x by all its extensions. We tried to switch with our setup to tornado 6.x and see quite some issues. Now we are back on tornado 5.1.1 again.

Is it possible to avoid the requirement of tornado>=6 for your extension?

**Comment by timkpaine** [comment]
This code would need to be modified to support older versions https://github.com/timkpaine/jupyterlab_iframe/blob/master/jupyterlab_iframe/proxy.py

**Comment by jhgoebbert** [comment]
Thank you for that hint. For now, we will stick to 0.0.11.
