### ISSUE TITLE
src of HTML-<iframe>

### ISSUE THREAD

**Issue by jhgoebbert** [timkpaine/jupyterlab_iframe#39]
Hi timkpaine,

I love the welcome page of jupyterlab_iframe. 
For some reason the generated HTML-code for the welcome page includes "iframes/proxy?path". I can reproduce it with jupyterlab_iframe 0.0.11 installed with jupyter 0.35.6 .

The HTML-code reads like this:
<iframe baseuri="http://localhost:8888/" src="iframes/proxy?path=http://www.fz-juelich.de/jsc"></iframe>
but should be
<iframe baseuri="http://localhost:8888/" src="http://www.fz-juelich.de/jsc"></iframe>

**Comment by timkpaine** [comment]
@jhgoebbert that is the auto-proxy code that happens when fetching the page fails:
https://github.com/timkpaine/jupyterlab_iframe/blob/master/src/index.ts#L65

**Comment by jhgoebbert** [comment]
ah, sorry. This code is from version 0.0.12 - I accidentally installed the new version instead of 0.0.11.

**Comment by jhgoebbert** [comment]
Hi timkpaine,

I have to reopen this issue ...

I wanted to downgrade to be compatible with tornado 5.1.1 and installed jupyterlab_iframe with
  >> jupyter labextension install jupyterlab_iframe@0.1.10
But looking at the code which is installed then in not version 0.1.10, but something close to version 0.1.12. It seems to me that 0.1.10 on github is not 0.1.10 on npmjs (https://www.npmjs.com/package/jupyterlab_iframe).
