### ISSUE TITLE
Issues with linked resources in the iframe

### ISSUE THREAD

**Issue by consideRatio** [timkpaine/jupyterlab_iframe#45]
## Opening up `https://www.google.com` I see...

![image](https://user-images.githubusercontent.com/3837114/66996040-41d73f00-f0d0-11e9-98b8-e2cb27eb577c.png)

## Because...
My browser end up trying to access something on my domain, that is in reality located on www.google.com domain, after a link referenced `/something` that resides on www.google.com.

```html
<iframe src="https://my-jupyterhub.com/user/erik/iframes/proxy?path=https://www.google.com">
  <!--
    The link below is making my browser attempt to fetch:
    https://my-jupyterhub.com/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png
    It should in this case instead try to fetch the same image but on the google.com domain.
  -->
  <img src="/images/branding/googlelogo/1x/googlelogo_white_background_color_272x92dp.png">
  <!-- ... -->
</iframe>
```

---

I'm not sure if this relates to #40 or not, so I decided to open a new issue. I'm also not sure if there is a good method to manage this situation in a sustainable way, perhaps sometimes links should act like this, but perhaps not always, I'm not sure.

**Comment by tom-butler** [comment]
I ran into the same issue, and it appears to be CORS related.

If the site you are trying to open doesn't set Access-Control-Request-Headers to be open then the jupyterlab_iframe extension will open it with a proxy, the proxy seems to have issues with linked resources like css etc, as they are relative links. 

The solution for me was to configure the CORS settings correctly on the endpoint I was trying to access. 

N.B. you'll probably have to clear your cache too, as the broken page will be cached.

**Comment by timkpaine** [comment]
There's only so much you can do, if a website doesn't want you to embed it it's always going to be difficult to do so!
