### ISSUE TITLE
missing ujson dependency

### ISSUE THREAD

**Issue by cboos** [timkpaine/jupyterlab_iframe#6]
Hello, I just installed the extension by following the steps listed in the README:
```
pip install jupyterlab_iframe
jupyter labextension install jupyterlab_iframe
jupyter serverextension enable --py jupyterlab_iframe
```

But the last step failed:
```
$ jupyter serverextension enable --py jupyterlab_iframe
Enabling: jupyterlab_iframe.extension
- Writing config: C:\Users\cboos\.jupyter
    - Validating...
Error loading server extension jupyterlab_iframe.extension
      X is jupyterlab_iframe.extension importable?
```

Looking closer:
```
$ jupyter serverextension list
config dir: C:\Users\cboos\.jupyter
    jupyterlab_iframe.extension enabled
    - Validating...
Error loading server extension jupyterlab_iframe.extension
      X is jupyterlab_iframe.extension importable?
config dir: c:\dev\python36\etc\jupyter
    jupyterlab enabled
    - Validating...
      jupyterlab  ok

$ python
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import jupyterlab_iframe.extension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Dev\Python36\lib\site-packages\jupyterlab_iframe\extension.py", line 1, in <module>
    import ujson
ModuleNotFoundError: No module named 'ujson'
>>> exit()

$ pip install ujson
Collecting ujson
  Downloading ujson-1.35.tar.gz (192kB)
    100% |████████████████████████████████| 194kB 936kB/s
Installing collected packages: ujson
  Running setup.py install for ujson ... done
Successfully installed ujson-1.35

$ jupyter serverextension list
config dir: C:\Users\cboos\.jupyter
    jupyterlab_iframe.extension enabled
    - Validating...
      jupyterlab_iframe.extension  ok
config dir: c:\dev\python36\etc\jupyter
    jupyterlab enabled
    - Validating...
      jupyterlab  ok
```

So it looks like the ujson package should be listed as a required dependency!

After that it worked. Well, sort of! Some URLs display just fine (e.g. Wikipedia), others won't for various reasons:
 - Refused to display 'https://github.com/topics/jupyterlab-extension' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
 - Refused to display 'https://stackoverflow.com/questions/34446172/open-url-in-new-tab-from-ipython-notebook-jupyter-cell' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
Would be nice if such errors could be displayed instead of just showing a blank tab...

But it's an useful extension despite of these limitations, so thanks anyway!

**Comment by timkpaine** [comment]
Some URLs forbid being displayed in iframe, as you've discovered. The easiest example is www.google.com

**Comment by cboos** [comment]
I've never used the requirements.txt mechanism, but it seems that having such a file won't play a role when calling `pip install jupyterlab_iframe`. This general dependency on `ujson` should rather be listed in the `install_requires` in setup.py (cf. https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires).

**Comment by timkpaine** [comment]
https://github.com/timkpaine/jupyterlab_iframe/issues/11

**Comment by jacobtomlinson** [comment]
For dependencies to be installed when installing this module with pip they also need to be in the `setup.py`.

**Comment by timkpaine** [comment]
this forces satisfaction of those by default (unless you do something like `pip install --no-deps`). I generally avoid this on all my packages because 1, I dont actually want to look for the minimum compatible version and 2, I dont want to set it to the current version in case people are using older version of packages.

**Comment by jacobtomlinson** [comment]
I'm not sure I follow. When installing a package with pip does not check the `requirements.txt` for further dependencies. 

As you are distributing this package I would recommend including your dependencies so that the instructions in the README work as expected.

This conversation may be superseded by #22 anyway if you're happy with that change.

**Comment by timkpaine** [comment]
the point is if someone is installing one package, they dont necessarily want to install all my specific dependency versions. an older ujson may work perfectly well, im just too lazy to check, and somebody may have a better reason (e.g. I dont enforce pandas versions on my stuff, it changes every version).
