### ISSUE TITLE
preview a streamlit app in an iframe

### ISSUE THREAD

**Issue by johnstantongeddes** [timkpaine/jupyterlab_iframe#61]
I'm starting to work with [streamlit](https://www.streamlit.io/), and would like to be able to see a preview of the app within JupyterLab. I installed this extension and confirmed that I can open an external page such as www.google.com, but when I try to load `http://localhost:port` it fails. Note that I'm not running JL locally, but hosted in AWS via Kubernetes which may cause some port routing issues I don't understand. I realize that this may be a Jupyter config issue moreso than this specific plug-in, but thought I'd try here first to see if you have any suggestions. Thanks! 

![Screen Shot 2020-06-24 at 10 40 04 AM](https://user-images.githubusercontent.com/3649798/85871698-c53b4b00-b79c-11ea-979e-5c09868c339d.png)

**Comment by timkpaine** [comment]
You're getting a 500 error so the jupyter logs should have information about what is going on

**Comment by johnstantongeddes** [comment]
@timkpaine Thanks for the quick response -- I'll dig into this and provide an update. I just realized that my installation is an old (v1.2) and that may be the problem. My apologies if this turns out to be the case.
