### ISSUE TITLE
iFrame not showing up in the menu

### ISSUE THREAD

**Issue by eric-valente** [timkpaine/jupyterlab_iframe#67]
Hi!

I'm running Jupyter lab 2.2.8 and followed these install instructions: 

pip install jupyterlab_iframe
jupyter labextension install jupyterlab_iframe
jupyter serverextension enable --py jupyterlab_iframe

Installs fine, but after rebuild I do not see this sites section in my menu:
![image](https://user-images.githubusercontent.com/35536427/97201088-46b4e100-176f-11eb-8273-670672fc3d1b.png)

![image](https://user-images.githubusercontent.com/35536427/97200955-1bca8d00-176f-11eb-82b9-c5cbe97a7710.png)

**Comment by timkpaine** [comment]
what is the result of `jupyter labextension list`? do other extensions install?

**Comment by ofekengel** [comment]
Sites will not appear in menu section (launcher in jupyterlab's terms). It is a feature I wrote and opened a pull request for :)
